# Generated by Django 5.0.4 on 2024-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
